package analysis

import (
	"bufio"
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"github.com/DataDog/datadog-saist/internal/model"
	"github.com/bmatcuk/doublestar/v4"
)

const (
	ProtoBufHeader = "Generated by the protocol buffer compiler.  DO NOT EDIT!"
	ThriftHeader   = "Autogenerated by Thrift Compiler"

	// Max number of characters we use at the file header to detect if this is a generated file.
	MaxHeaderSize = 400
)

// ---------- Glob patterns ----------

// DEFAULT_PATHS: parent folders that usually contain tests/specs.
var defaultTestPaths = []string{
	"**/test/**/*",
	"**/tests/**/*",
	"**/spec/**/*",
	"**/specs/**/*",
	"**/testcases/**/*",
	"**/testing/**/*",
	"**/__test__/**/*",
	"**/__tests__/**/*",
}

// DEFAULT_FILENAMES: expansions of "**/*[_.]{test,tests,spec,specs}.*"
var defaultTestFilenames = []string{
	// *_test.*, *_tests.*, *_spec.*, *_specs.*
	"**/*_test.*",
	"**/*_tests.*",
	"**/*_spec.*",
	"**/*_specs.*",
	// *.test.*, *.tests.*, *.spec.*, *.specs.*
	"**/*.test.*",
	"**/*.tests.*",
	"**/*.spec.*",
	"**/*.specs.*",
}

var goTestPathPatterns = []string{
	// go test convention
	"**/*_test.go",
	// mocks
	"**/mock_*.go",
	"**/*_mock.go",
}

// Python-specific path patterns (from Rust)
var pythonTestPathPatterns = []string{
	"**/features/steps/*.py",
	"**/features/environment.py",
	"**/test*.py",
	"**/*test_*.py",
	"**/*_test.py",
}

var DefaultIgnoredGlobs = []string{
	"**/node_modules/**/*",
	"**/jspm_packages/**/*",
	"**/.next/**/*",
	"**/.vuepress/**/*",
	"**/venv/**/*",
	"**/__pycache__/**/*",
	"**/_vendor/bundle/ruby/**/*",
	"**/.vendor/bundle/ruby/**/*",
	"**/.bundle/**/*",
	"**/.gradle/**/*",
	"**/TemporaryGeneratedFile_.*.cs",
	"**/*.designer.cs",
	"**/*.generated.cs",
	"**/*.g.cs",
	"**/*.g.i.cs",
}

func isGeneratedFileSuffix(path string) bool {
	return strings.HasSuffix(path, ".pb.go") ||
		strings.HasSuffix(path, "_pb2.py") ||
		strings.HasSuffix(path, ".generated.go")
}

func ShouldIgnorePath(path string) bool {
	// Normalize slashes for cross-platform matching
	p := filepath.ToSlash(path)

	for _, pattern := range DefaultIgnoredGlobs {
		match, err := doublestar.PathMatch(pattern, p)
		if err == nil && match {
			return true
		}
	}
	return false
}

// IsGeneratedFile returns true if a file is likely generated based on simple
// header heuristics. We only look at the first MaxHeaderSize bytes of the file.
func IsGeneratedFile(path string, language model.Language) (bool, error) {
	fullContent, err := os.ReadFile(path) // nolint: gosec
	if err != nil {
		return false, fmt.Errorf("failed to read file %s: %w", path, err)
	}

	return IsGeneratedFileFromContent(fullContent, path, language), nil
}

// IsGeneratedFileFromContent checks if content is generated without reading from disk.
// Use this when file content is already loaded to avoid redundant I/O.
// nolint: gocyclo
func IsGeneratedFileFromContent(fullContent []byte, path string, language model.Language) bool {
	// Limit to first MaxHeaderSize bytes (Rust code uses chars; for most cases
	// bytes are fine. If you care about runes, you can trim by rune count instead.)
	headerContent := fullContent
	if len(headerContent) > MaxHeaderSize {
		headerContent = headerContent[:MaxHeaderSize]
	}

	content := string(headerContent)

	switch language {
	case model.Go:
		return strings.Contains(content, "Code generated by") ||
			strings.Contains(content, ProtoBufHeader) ||
			strings.Contains(content, ThriftHeader) ||
			isGeneratedFileSuffix(path)

	case model.Java:
		return strings.Contains(content, "generated by the protocol buffer compiler") ||
			strings.Contains(content, ProtoBufHeader) ||
			strings.Contains(content, ThriftHeader) ||
			isGeneratedFileSuffix(path)

	case model.Python:
		return strings.Contains(content, "Generated protocol buffer code") ||
			strings.Contains(content, "Generated by the gRPC Python protocol compiler plugin") ||
			strings.Contains(content, "Code generated by") ||
			strings.Contains(content, ProtoBufHeader) ||
			strings.Contains(content, ThriftHeader) ||
			isGeneratedFileSuffix(path)
	default:
		return isGeneratedFileSuffix(path)
	}
}

// IsTestFile returns true if the file is likely a test file (or test-related helper)
// for the given language, based on path + imports.
func IsTestFile(path string, language model.Language) (bool, error) {
	// 1. Path-based heuristics (cheap, no I/O)
	if hasTestLikePath(path, language) {
		return true, nil
	}

	// 2. Import-based heuristics
	src, err := os.ReadFile(path) // nolint: gosec
	if err != nil {
		// Could not read => fail open as "not a test" rather than erroring the whole scan.
		return false, nil
	}

	if hasTestLikeImport(language, string(src), path) {
		return true, nil
	}

	return false, nil
}

// IsTestFileFromContent checks if content is a test file without reading from disk.
// Use this when file content is already loaded to avoid redundant I/O.
func IsTestFileFromContent(content []byte, path string, language model.Language) bool {
	// 1. Path-based heuristics (cheap, no I/O)
	if hasTestLikePath(path, language) {
		return true
	}

	// 2. Import-based heuristics
	if hasTestLikeImport(language, string(content), path) {
		return true
	}

	return false
}

// IsTestFileByPath checks if a file is a test file based only on path patterns (no content needed).
// Use this for early filtering before content is available.
func IsTestFileByPath(path string, language model.Language) bool {
	return hasTestLikePath(path, language)
}

// IsTestFileByContent checks if a file is a test file based on content (imports).
// Use this after file content is loaded.
func IsTestFileByContent(content []byte, path string, language model.Language) bool {
	return hasTestLikeImport(language, string(content), path)
}

// IsGeneratedFileByPath checks if a file is generated based only on path/suffix (no content needed).
// Use this for early filtering before content is available.
func IsGeneratedFileByPath(path string) bool {
	return isGeneratedFileSuffix(path)
}

// IsGeneratedFileByContent checks if a file is generated based on content headers.
// Use this after file content is loaded.
func IsGeneratedFileByContent(content []byte, path string, language model.Language) bool {
	// Limit to first MaxHeaderSize bytes
	headerContent := content
	if len(headerContent) > MaxHeaderSize {
		headerContent = headerContent[:MaxHeaderSize]
	}

	header := string(headerContent)

	switch language {
	case model.Go:
		return strings.Contains(header, "Code generated by") ||
			strings.Contains(header, ProtoBufHeader) ||
			strings.Contains(header, ThriftHeader)

	case model.Java:
		return strings.Contains(header, "generated by the protocol buffer compiler") ||
			strings.Contains(header, ProtoBufHeader) ||
			strings.Contains(header, ThriftHeader)

	case model.Python:
		return strings.Contains(header, "Generated protocol buffer code") ||
			strings.Contains(header, "Generated by the gRPC Python protocol compiler plugin") ||
			strings.Contains(header, "Code generated by") ||
			strings.Contains(header, ProtoBufHeader) ||
			strings.Contains(header, ThriftHeader)
	default:
		return false
	}
}

// ---------- Path-based detection ----------

func matchesAnyGlob(path string, patterns []string) bool {
	p := filepath.ToSlash(path)
	for _, pat := range patterns {
		match, err := doublestar.PathMatch(pat, p)
		if err == nil && match {
			return true
		}
	}
	return false
}

func hasTestLikePath(path string, language model.Language) bool {
	switch language {
	case model.Go:
		// Go uses its own patterns only (like Rust implementation)
		return matchesAnyGlob(path, goTestPathPatterns)

	case model.Java:
		// Java: default test folders only
		return matchesAnyGlob(path, defaultTestPaths)

	case model.Python:
		// Python: default folders + default filenames + extra pytest/nose/behave patterns
		var patterns []string
		patterns = append(patterns, defaultTestPaths...)
		patterns = append(patterns, defaultTestFilenames...)
		patterns = append(patterns, pythonTestPathPatterns...)
		return matchesAnyGlob(path, patterns)

	default:
		// For other languages we don't classify here
		return false
	}
}

// ---------- Import-based detection ----------

func hasTestLikeImport(language model.Language, code, path string) bool {
	switch language {
	case model.Go:
		return goHasTestLikeImport(code, path)
	case model.Java:
		return javaHasTestLikeImport(code)
	case model.Python:
		return pythonHasTestLikeImport(code)
	default:
		return false
	}
}

// ----- Go import detection -----

func goHasTestLikeImport(code, path string) bool {
	fset := token.NewFileSet()
	// Parse only imports; we don't need full AST.
	file, err := parser.ParseFile(fset, path, code, parser.ImportsOnly)
	if err != nil || file == nil {
		return false
	}

	testImportPrefixes := []string{
		"github.com/go-check/check",
		"github.com/onsi/ginkgo",
		"github.com/h2non/gock",
		"github.com/smartystreets/goconvey",
		"github.com/onsi/gomega",
		"github.com/golang/mock",
		"go.uber.org/mock",
		"github.com/petergtz/pegomock",
		"testing",
		"github.com/stretchr/testify",
	}

	for _, spec := range file.Imports {
		raw := strings.Trim(spec.Path.Value, `"`) // "testing" or "github.com/stretchr/testify/require"
		for _, prefix := range testImportPrefixes {
			if raw == prefix || strings.HasPrefix(raw, prefix+"/") {
				return true
			}
		}
	}
	return false
}

// ----- Java import detection -----
func javaHasTestLikeImport(code string) bool {
	javaTestPrefixes := []string{
		"org.apache.camel.test",
		"org.awaitility",
		"org.jboss.arquillian",
		"org.assertj",
		"io.cucumber",
		"org.dbunit",
		"org.easymock",
		"org.jbehave",
		"org.openjdk.jmh",
		"org.junit",
		"com.intuit.karate",
		"org.mockito",
		"au.com.dius.pact",
		"org.powermock",
		"io.restassured",
		"org.seleniumhq.selenium",
		"org.openqa.selenium",
		"org.spockframework",
		"org.testcontainers",
		"org.testfx",
		"org.testng",
		"com.github.tomakehurst.wiremock",
	}

	scanner := bufio.NewScanner(strings.NewReader(code))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if !strings.HasPrefix(line, "import ") {
			continue
		}
		// Strip "import" and optional "static".
		line = strings.TrimSpace(strings.TrimPrefix(line, "import"))
		if strings.HasPrefix(line, "static ") {
			line = strings.TrimSpace(strings.TrimPrefix(line, "static"))
		}
		// Drop trailing ';'
		if i := strings.Index(line, ";"); i >= 0 {
			line = line[:i]
		}
		// Now line should be a FQN like org.junit.Assert or org.mockito.Mockito
		for _, prefix := range javaTestPrefixes {
			if line == prefix || strings.HasPrefix(line, prefix+".") {
				return true
			}
		}
	}
	return false
}

// ----- Python import detection -----
func pythonHasTestLikeImport(code string) bool {
	pyTestPrefixes := []string{
		"behave",
		"doctest",
		"hypothesis",
		"nox",
		"pytest",
		"pytest_bdd",
		"testify",
		"unittest",
		"unittest2",
	}

	scanner := bufio.NewScanner(strings.NewReader(code))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Handle "import X" or "import X as Y"
		if strings.HasPrefix(line, "import ") {
			rest := strings.TrimSpace(strings.TrimPrefix(line, "import"))
			// Basic split: "pytest", "pytest as p"
			fields := strings.Fields(rest)
			if len(fields) > 0 {
				mod := fields[0] // first module in "import pytest"
				if pythonImportMatches(mod, pyTestPrefixes) {
					return true
				}
			}
		}

		// Handle "from X import Y"
		if strings.HasPrefix(line, "from ") {
			rest := strings.TrimSpace(strings.TrimPrefix(line, "from"))
			fields := strings.Fields(rest)
			if len(fields) > 0 {
				mod := fields[0] // module in "from pytest import some_fixture"
				if pythonImportMatches(mod, pyTestPrefixes) {
					return true
				}
			}
		}
	}
	return false
}

func pythonImportMatches(module string, prefixes []string) bool {
	for _, prefix := range prefixes {
		if module == prefix || strings.HasPrefix(module, prefix+".") {
			return true
		}
	}
	return false
}
