package analysis

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/DataDog/datadog-saist/internal/model"
	"github.com/stretchr/testify/assert"
)

// helper: create a temp file with given content and (optional) name suffix.
func writeTempFile(t *testing.T, suffix string, content string) string {
	t.Helper()

	dir := t.TempDir()
	name := "test" + suffix
	path := filepath.Join(dir, name)

	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("failed to write temp file %s: %v", path, err)
	}
	return path
}

func TestIsGeneratedFile_Go_Headers(t *testing.T) {
	// not generated
	path := writeTempFile(t, ".go", "package main\n\nfunc f() {}\n")
	gen, err := IsGeneratedFile(path, model.Go)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if gen {
		t.Fatalf("expected non-generated Go file")
	}

	// "Code generated by"
	path = writeTempFile(t, ".go", "// Code generated by MockGen. DO NOT EDIT.\npackage main\n")
	gen, err = IsGeneratedFile(path, model.Go)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !gen {
		t.Fatalf("expected generated Go file (Code generated by...)")
	}

	// PROTOBUF_HEADER
	path = writeTempFile(t, ".go", "// "+ProtoBufHeader+"\npackage main\n")
	gen, err = IsGeneratedFile(path, model.Go)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !gen {
		t.Fatalf("expected generated Go file (ProtoBufHeader)")
	}

	// THRIFT_HEADER
	path = writeTempFile(t, ".go", "// "+ThriftHeader+"\npackage main\n")
	gen, err = IsGeneratedFile(path, model.Go)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !gen {
		t.Fatalf("expected generated Go file (ThriftHeader)")
	}
}

func TestIsGeneratedFile_Go_Suffixes(t *testing.T) {
	// .pb.go should be treated as generated even without header
	path := writeTempFile(t, ".pb.go", "package main\n\nfunc f() {}\n")
	gen, err := IsGeneratedFile(path, model.Go)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !gen {
		t.Fatalf("expected generated Go file based on .pb.go suffix")
	}

	// .generated.go should be treated as generated
	path = writeTempFile(t, ".generated.go", "package main\n\nfunc f() {}\n")
	gen, err = IsGeneratedFile(path, model.Go)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !gen {
		t.Fatalf("expected generated Go file based on .generated.go suffix")
	}
}

func TestIsGeneratedFile_Java(t *testing.T) {
	// not generated
	path := writeTempFile(t, ".java", "class Foobar {}")
	gen, err := IsGeneratedFile(path, model.Java)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if gen {
		t.Fatalf("expected non-generated Java file")
	}

	// "generated by the protocol buffer compiler"
	path = writeTempFile(t, ".java", "// generated by the protocol buffer compiler\nclass Foobar {}")
	gen, err = IsGeneratedFile(path, model.Java)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !gen {
		t.Fatalf("expected generated Java file (proto compiler string)")
	}

	// PROTOBUF_HEADER
	path = writeTempFile(t, ".java", "// "+ProtoBufHeader+"\nclass Foobar {}")
	gen, err = IsGeneratedFile(path, model.Java)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !gen {
		t.Fatalf("expected generated Java file (ProtoBufHeader)")
	}

	// THRIFT_HEADER
	path = writeTempFile(t, ".java", "// "+ThriftHeader+"\nclass Foobar {}")
	gen, err = IsGeneratedFile(path, model.Java)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !gen {
		t.Fatalf("expected generated Java file (ThriftHeader)")
	}
}

func TestIsGeneratedFile_Python(t *testing.T) {
	// not generated
	path := writeTempFile(t, ".py", "def foo():\n    pass\n")
	gen, err := IsGeneratedFile(path, model.Python)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if gen {
		t.Fatalf("expected non-generated Python file")
	}

	// "Generated protocol buffer code"
	path = writeTempFile(t, ".py", "# Generated protocol buffer code\ndef foo():\n    pass\n")
	gen, err = IsGeneratedFile(path, model.Python)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !gen {
		t.Fatalf("expected generated Python file (Generated protocol buffer code)")
	}

	// "Generated by the gRPC Python protocol compiler plugin"
	path = writeTempFile(t, ".py", "# Generated by the gRPC Python protocol compiler plugin\ndef foo():\n    pass\n")
	gen, err = IsGeneratedFile(path, model.Python)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !gen {
		t.Fatalf("expected generated Python file (gRPC compiler plugin)")
	}

	// "Code generated by"
	path = writeTempFile(t, ".py", "# Code generated by some tool\ndef foo():\n    pass\n")
	gen, err = IsGeneratedFile(path, model.Python)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !gen {
		t.Fatalf("expected generated Python file (Code generated by)")
	}

	// PROTOBUF_HEADER
	path = writeTempFile(t, ".py", "# "+ProtoBufHeader+"\ndef foo():\n    pass\n")
	gen, err = IsGeneratedFile(path, model.Python)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !gen {
		t.Fatalf("expected generated Python file (ProtoBufHeader)")
	}

	// THRIFT_HEADER
	path = writeTempFile(t, ".py", "# "+ThriftHeader+"\ndef foo():\n    pass\n")
	gen, err = IsGeneratedFile(path, model.Python)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !gen {
		t.Fatalf("expected generated Python file (ThriftHeader)")
	}
}

func TestIsGeneratedFile_DefaultSuffixOnly(t *testing.T) {
	// For a language not explicitly handled in the switch, we still use suffixes.
	// Pick some other language constant if you have one, or construct a fake one.
	// Here assume model.Language has something like model.TypeScript; if not, adjust.
	path := writeTempFile(t, ".pb.go", "package main\n\nfunc f() {}\n")

	// Use a language that hits the default branch in the switch.
	gen, err := IsGeneratedFile(path, model.LanguageUnknown)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !gen {
		t.Fatalf("expected generated file based on suffix in default branch")
	}
}

func TestIsGeneratedFile_FileNotFound(t *testing.T) {
	_, err := IsGeneratedFile("this/does/not/exist.go", model.Go)
	if err == nil {
		t.Fatalf("expected error for non-existent file")
	}
}

func TestIsGeneratedFile_Elixir(t *testing.T) {
	path := writeTempFile(t, ".pb.ex", "defmodule Generated.Message do\nend\n")
	generated, err := IsGeneratedFile(path, model.Elixir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !generated {
		t.Fatalf("expected generated Elixir protobuf file")
	}
}

func TestIsTestFile_Elixir(t *testing.T) {
	if !IsTestFileFromContent([]byte("use ExUnit.Case, async: true"), "lib/example.ex", model.Elixir) {
		t.Fatalf("expected ExUnit module to be classified as a test")
	}
	if !IsTestFileFromContent(nil, "test/example_test.exs", model.Elixir) {
		t.Fatalf("expected *_test.exs file to be classified as a test")
	}
}

func TestIsTestFileByPathSwift(t *testing.T) {
	assert.True(t, IsTestFileByPath("Tests/AppTests/FeatureTests.swift", model.Swift))
	assert.False(t, IsTestFileByPath("Sources/App/Feature.swift", model.Swift))
}

func TestDartFileClassification(t *testing.T) {
	assert.True(t, IsTestFileFromContent(nil, "integration_test/app_test.dart", model.Dart))
	assert.True(t, IsTestFileFromContent([]byte("import 'package:flutter_test/flutter_test.dart';"), "lib/widget.dart", model.Dart))
	assert.True(t, IsGeneratedFileFromContent([]byte("// GENERATED CODE - DO NOT MODIFY BY HAND"), "lib/model.dart", model.Dart))
	assert.True(t, IsGeneratedFileFromContent(nil, "lib/model.freezed.dart", model.Dart))
	assert.True(t, ShouldIgnorePath("example/.dart_tool/build/generated.dart"))
	assert.False(t, ShouldIgnorePath("example/build/generated.go"))
}

func TestIsGeneratedFileCpp(t *testing.T) {
	path := writeTempFile(t, ".pb.cc", "namespace generated {}")
	generated, err := IsGeneratedFile(path, model.Cpp)
	assert.NoError(t, err)
	assert.True(t, generated)
}

func TestIsTestFileCpp(t *testing.T) {
	assert.True(t, IsTestFileFromContent(nil, "tests/server_test.cpp", model.Cpp))
	assert.True(t, IsTestFileFromContent(nil, "tests/server_unittest.c++", model.Cpp))
	assert.True(t, IsTestFileFromContent([]byte("#include <gtest/gtest.h>"), "src/server.cpp", model.Cpp))
	assert.True(t, IsTestFileFromContent([]byte("# include \"gmock/gmock.h\""), "src/server.cpp", model.Cpp))
	assert.True(t, IsTestFileFromContent([]byte("#include <boost/test/unit_test.hpp>"), "src/server.cpp", model.Cpp))
	assert.False(t, IsTestFileFromContent([]byte("const char* header = \"gtest/gtest.h\";"), "src/server.cpp", model.Cpp))
	assert.False(t, IsTestFileFromContent([]byte("/*\n#include <gtest/gtest.h>\n*/"), "src/server.cpp", model.Cpp))
	assert.False(t, IsTestFileFromContent([]byte("const char* fixture = R\"(\n#include <gtest/gtest.h>\n)\";"), "src/server.cpp", model.Cpp))
	assert.False(t, IsTestFileFromContent([]byte("#include <vector>"), "src/server.cpp", model.Cpp))
}

func TestShouldIgnoreCppBuildOutput(t *testing.T) {
	assert.True(t, ShouldIgnorePath("project/build/generated.cpp"))
	assert.True(t, ShouldIgnorePath("project/cmake-build-debug/generated.hpp"))
	assert.True(t, ShouldIgnorePath("project/_deps/library/source.cc"))
	assert.False(t, ShouldIgnorePath("project/build/generated.go"))
	assert.False(t, ShouldIgnorePath("project/src/build_helpers/source.cpp"))
}
