package analysis

import (
	"bufio"
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/DataDog/datadog-saist/internal/model"
	"github.com/bmatcuk/doublestar/v4"
)

const (
	ProtoBufHeader        = "Generated by the protocol buffer compiler.  DO NOT EDIT!"
	ThriftHeader          = "Autogenerated by Thrift Compiler"
	GeneratedByMarker     = "Code generated by"
	RustGeneratedMarker   = "@generated"
	ElixirGeneratedMarker = "This file was generated"
	DartGeneratedMarker   = "GENERATED CODE - DO NOT MODIFY BY HAND"
	DartGeneratedPackage  = "DO NOT EDIT. This is code generated via package:"

	// Max number of characters we use at the file header to detect if this is a generated file.
	MaxHeaderSize = 400
)

// ---------- Glob patterns ----------

// DEFAULT_PATHS: parent folders that usually contain tests/specs.
var defaultTestPaths = []string{
	"**/test/**/*",
	"**/tests/**/*",
	"**/spec/**/*",
	"**/specs/**/*",
	"**/testcases/**/*",
	"**/testing/**/*",
	"**/__test__/**/*",
	"**/__tests__/**/*",
}

// DEFAULT_FILENAMES: expansions of "**/*[_.]{test,tests,spec,specs}.*"
var defaultTestFilenames = []string{
	// *_test.*, *_tests.*, *_spec.*, *_specs.*
	"**/*_test.*",
	"**/*_tests.*",
	"**/*_spec.*",
	"**/*_specs.*",
	// *.test.*, *.tests.*, *.spec.*, *.specs.*
	"**/*.test.*",
	"**/*.tests.*",
	"**/*.spec.*",
	"**/*.specs.*",
}

var goTestPathPatterns = []string{
	// go test convention
	"**/*_test.go",
	// mocks
	"**/mock_*.go",
	"**/*_mock.go",
}

// Python-specific path patterns (from Rust)
var pythonTestPathPatterns = []string{
	"**/features/steps/*.py",
	"**/features/environment.py",
	"**/test*.py",
	"**/*test_*.py",
	"**/*_test.py",
}

var javascriptTestPathPatterns = []string{
	"**/__mocks__/**/*.js",
	"**/__mocks__/**/*.jsx",
	"**/__mocks__/**/*.mjs",
}

var typescriptTestPathPatterns = []string{
	"**/__mocks__/**/*.ts",
	"**/__mocks__/**/*.tsx",
	"**/__mocks__/**/*.mts",
	"**/__mocks__/**/*.cts",
}

var kotlinTestPathPatterns = []string{
	"**/*Test.kt",
	"**/*Tests.kt",
	"**/*Spec.kt",
	"**/*IT.kt",
}

var phpTestPathPatterns = []string{
	"**/*Test.php",
	"**/*Tests.php",
	"**/*TestCase.php",
	"**/*Spec.php",
}

var rubyTestPathPatterns = []string{
	"**/*_spec.rb",
	"**/spec/**",
	"**/*_test.rb",
}

var rustTestPathPatterns = []string{
	"**/tests/**/*",
	"**/tests.rs",
}

var elixirTestPathPatterns = []string{
	"**/*_test.exs",
	"**/test_helper.exs",
}

var swiftTestPathPatterns = []string{
	"**/*Tests.swift",
	"**/*Test.swift",
	"**/*Spec.swift",
	"**/*UITests.swift",
}

var dartTestPathPatterns = []string{
	"**/test/**/*.dart",
	"**/integration_test/**/*.dart",
	"**/*_test.dart",
}

var DefaultIgnoredGlobs = []string{
	"**/node_modules/**/*",
	"**/jspm_packages/**/*",
	"**/.next/**/*",
	"**/.vuepress/**/*",
	"**/venv/**/*",
	"**/__pycache__/**/*",
	"**/_vendor/bundle/ruby/**/*",
	"**/.vendor/bundle/ruby/**/*",
	"**/.bundle/**/*",
	"**/.gradle/**/*",
	"**/TemporaryGeneratedFile_.*.cs",
	"**/*.designer.cs",
	"**/*.generated.cs",
	"**/*.g.cs",
	"**/*.g.i.cs",
	"**/*.min.js",
	"**/dist/**/*.js",
	"**/build/**/*.js",
	"**/*.d.ts",
	"**/dist/**/*.ts",
	"**/build/**/*.ts",
}

func isGeneratedFileSuffix(path string) bool {
	return strings.HasSuffix(path, ".pb.go") ||
		strings.HasSuffix(path, "_pb2.py") ||
		strings.HasSuffix(path, ".pb.ex") ||
		strings.HasSuffix(path, ".generated.go") ||
		isDartGeneratedFileSuffix(path)
}

func isDartGeneratedFileSuffix(path string) bool {
	return strings.HasSuffix(path, ".g.dart") ||
		strings.HasSuffix(path, ".freezed.dart") ||
		strings.HasSuffix(path, ".mocks.dart") ||
		strings.HasSuffix(path, ".pb.dart") ||
		strings.HasSuffix(path, ".pbenum.dart") ||
		strings.HasSuffix(path, ".pbjson.dart") ||
		strings.HasSuffix(path, ".pbserver.dart")
}

func ShouldIgnorePath(path string) bool {
	// Normalize slashes for cross-platform matching
	p := filepath.ToSlash(path)
	if strings.EqualFold(filepath.Ext(p), ".dart") && matchesAnyGlob(p, []string{
		"**/.dart_tool/**/*",
		"**/.pub-cache/**/*",
		"**/build/**/*",
	}) {
		return true
	}

	for _, pattern := range DefaultIgnoredGlobs {
		match, err := doublestar.PathMatch(pattern, p)
		if err == nil && match {
			return true
		}
	}
	return false
}

// IsGeneratedFile returns true if a file is likely generated based on simple
// header heuristics. We only look at the first MaxHeaderSize bytes of the file.
func IsGeneratedFile(path string, language model.Language) (bool, error) {
	fullContent, err := os.ReadFile(path) // nolint: gosec
	if err != nil {
		return false, fmt.Errorf("failed to read file %s: %w", path, err)
	}

	return IsGeneratedFileFromContent(fullContent, path, language), nil
}

// IsGeneratedFileFromContent checks if content is generated without reading from disk.
// Use this when file content is already loaded to avoid redundant I/O.
// nolint: gocyclo
func IsGeneratedFileFromContent(fullContent []byte, path string, language model.Language) bool {
	// Limit to first MaxHeaderSize bytes (Rust code uses chars; for most cases
	// bytes are fine. If you care about runes, you can trim by rune count instead.)
	headerContent := fullContent
	if len(headerContent) > MaxHeaderSize {
		headerContent = headerContent[:MaxHeaderSize]
	}

	content := string(headerContent)

	switch language {
	case model.Go:
		return strings.Contains(content, GeneratedByMarker) ||
			strings.Contains(content, ProtoBufHeader) ||
			strings.Contains(content, ThriftHeader) ||
			isGeneratedFileSuffix(path)

	case model.Java:
		return strings.Contains(content, "generated by the protocol buffer compiler") ||
			strings.Contains(content, ProtoBufHeader) ||
			strings.Contains(content, ThriftHeader) ||
			isGeneratedFileSuffix(path)

	case model.Python:
		return strings.Contains(content, "Generated protocol buffer code") ||
			strings.Contains(content, "Generated by the gRPC Python protocol compiler plugin") ||
			strings.Contains(content, GeneratedByMarker) ||
			strings.Contains(content, ProtoBufHeader) ||
			strings.Contains(content, ThriftHeader) ||
			isGeneratedFileSuffix(path)

	case model.JavaScript:
		return strings.Contains(content, GeneratedByMarker) ||
			strings.HasSuffix(path, ".min.js")

	case model.TypeScript:
		return strings.Contains(content, GeneratedByMarker) ||
			strings.HasSuffix(path, ".d.ts")

	case model.Kotlin:
		return strings.Contains(content, GeneratedByMarker) ||
			strings.Contains(content, ProtoBufHeader) ||
			strings.Contains(content, ThriftHeader)

	case model.PHP:
		return strings.Contains(content, GeneratedByMarker)

	case model.Rust:
		return strings.Contains(content, GeneratedByMarker) ||
			strings.Contains(content, RustGeneratedMarker) ||
			strings.Contains(content, ProtoBufHeader) ||
			strings.Contains(content, ThriftHeader)

	case model.Elixir:
		return strings.Contains(content, ElixirGeneratedMarker) ||
			strings.Contains(content, GeneratedByMarker) ||
			strings.Contains(content, ProtoBufHeader) ||
			strings.Contains(content, ThriftHeader) ||
			isGeneratedFileSuffix(path)

	case model.Swift:
		return strings.Contains(content, GeneratedByMarker) ||
			strings.Contains(content, ProtoBufHeader) ||
			strings.Contains(content, ThriftHeader)

	case model.Dart:
		return strings.Contains(content, DartGeneratedMarker) ||
			strings.Contains(content, DartGeneratedPackage) ||
			isDartGeneratedFileSuffix(path)

	default:
		return isGeneratedFileSuffix(path)
	}
}

// IsTestFile returns true if the file is likely a test file (or test-related helper)
// for the given language, based on path + imports.
func IsTestFile(path string, language model.Language) (bool, error) {
	// 1. Path-based heuristics (cheap, no I/O)
	if hasTestLikePath(path, language) {
		return true, nil
	}

	// 2. Import-based heuristics
	src, err := os.ReadFile(path) // nolint: gosec
	if err != nil {
		// Could not read => fail open as "not a test" rather than erroring the whole scan.
		return false, nil
	}

	if hasTestLikeImport(language, string(src), path) {
		return true, nil
	}

	return false, nil
}

// IsTestFileFromContent checks if content is a test file without reading from disk.
// Use this when file content is already loaded to avoid redundant I/O.
func IsTestFileFromContent(content []byte, path string, language model.Language) bool {
	// 1. Path-based heuristics (cheap, no I/O)
	if hasTestLikePath(path, language) {
		return true
	}

	// 2. Import-based heuristics
	if hasTestLikeImport(language, string(content), path) {
		return true
	}

	return false
}

// IsTestFileByPath checks if a file is a test file based only on path patterns (no content needed).
// Use this for early filtering before content is available.
func IsTestFileByPath(path string, language model.Language) bool {
	return hasTestLikePath(path, language)
}

// IsTestFileByContent checks if a file is a test file based on content (imports).
// Use this after file content is loaded.
func IsTestFileByContent(content []byte, path string, language model.Language) bool {
	return hasTestLikeImport(language, string(content), path)
}

// IsGeneratedFileByPath checks if a file is generated based only on path/suffix (no content needed).
// Use this for early filtering before content is available.
func IsGeneratedFileByPath(path string) bool {
	return isGeneratedFileSuffix(path)
}

// IsGeneratedFileByContent checks if a file is generated based on content headers.
// Use this after file content is loaded.
// nolint: gocyclo
func IsGeneratedFileByContent(content []byte, path string, language model.Language) bool {
	// Limit to first MaxHeaderSize bytes
	headerContent := content
	if len(headerContent) > MaxHeaderSize {
		headerContent = headerContent[:MaxHeaderSize]
	}

	header := string(headerContent)

	switch language {
	case model.Go:
		return strings.Contains(header, GeneratedByMarker) ||
			strings.Contains(header, ProtoBufHeader) ||
			strings.Contains(header, ThriftHeader)

	case model.Java:
		return strings.Contains(header, "generated by the protocol buffer compiler") ||
			strings.Contains(header, ProtoBufHeader) ||
			strings.Contains(header, ThriftHeader)

	case model.Python:
		return strings.Contains(header, "Generated protocol buffer code") ||
			strings.Contains(header, "Generated by the gRPC Python protocol compiler plugin") ||
			strings.Contains(header, GeneratedByMarker) ||
			strings.Contains(header, ProtoBufHeader) ||
			strings.Contains(header, ThriftHeader)

	case model.JavaScript:
		return strings.Contains(header, GeneratedByMarker)

	case model.TypeScript:
		return strings.Contains(header, GeneratedByMarker) ||
			strings.HasSuffix(path, ".d.ts")

	case model.Kotlin:
		return strings.Contains(header, GeneratedByMarker) ||
			strings.Contains(header, ProtoBufHeader) ||
			strings.Contains(header, ThriftHeader)

	case model.PHP:
		return strings.Contains(header, GeneratedByMarker)

	case model.Rust:
		return strings.Contains(header, GeneratedByMarker) ||
			strings.Contains(header, RustGeneratedMarker) ||
			strings.Contains(header, ProtoBufHeader) ||
			strings.Contains(header, ThriftHeader)

	case model.Elixir:
		return strings.Contains(header, ElixirGeneratedMarker) ||
			strings.Contains(header, GeneratedByMarker) ||
			strings.Contains(header, ProtoBufHeader) ||
			strings.Contains(header, ThriftHeader)

	case model.Swift:
		return strings.Contains(header, GeneratedByMarker) ||
			strings.Contains(header, ProtoBufHeader) ||
			strings.Contains(header, ThriftHeader)

	case model.Dart:
		return strings.Contains(header, DartGeneratedMarker) ||
			strings.Contains(header, DartGeneratedPackage)

	default:
		return false
	}
}

// ---------- Path-based detection ----------

func matchesAnyGlob(path string, patterns []string) bool {
	p := filepath.ToSlash(path)
	for _, pat := range patterns {
		match, err := doublestar.PathMatch(pat, p)
		if err == nil && match {
			return true
		}
	}
	return false
}

func hasTestLikePath(path string, language model.Language) bool {
	switch language {
	case model.Go:
		// Go uses its own patterns only (like Rust implementation)
		return matchesAnyGlob(path, goTestPathPatterns)

	case model.Java:
		// Java: default test folders only
		return matchesAnyGlob(path, defaultTestPaths)

	case model.Python:
		// Python: default folders + default filenames + extra pytest/nose/behave patterns
		var patterns []string
		patterns = append(patterns, defaultTestPaths...)
		patterns = append(patterns, defaultTestFilenames...)
		patterns = append(patterns, pythonTestPathPatterns...)
		return matchesAnyGlob(path, patterns)

	case model.JavaScript:
		// JavaScript: default folders + default filenames (*.test.js, *.spec.js) + Jest-specific
		var patterns []string
		patterns = append(patterns, defaultTestPaths...)
		patterns = append(patterns, defaultTestFilenames...)
		patterns = append(patterns, javascriptTestPathPatterns...)
		return matchesAnyGlob(path, patterns)

	case model.TypeScript:
		// TypeScript: same shape as JS — default folders + filenames + Jest mocks for ts/tsx/mts/cts
		var patterns []string
		patterns = append(patterns, defaultTestPaths...)
		patterns = append(patterns, defaultTestFilenames...)
		patterns = append(patterns, typescriptTestPathPatterns...)
		return matchesAnyGlob(path, patterns)

	case model.Kotlin:
		// Kotlin: default folders + filenames + Kotlin naming (FooTest.kt, FooSpec.kt)
		var patterns []string
		patterns = append(patterns, defaultTestPaths...)
		patterns = append(patterns, defaultTestFilenames...)
		patterns = append(patterns, kotlinTestPathPatterns...)
		return matchesAnyGlob(path, patterns)

	case model.PHP:
		// PHP: default folders + PHPUnit naming (FooTest.php, FooSpec.php)
		return matchesAnyGlob(path, slices.Concat(defaultTestPaths, defaultTestFilenames, phpTestPathPatterns))

	case model.Ruby:
		// Ruby: default folders + RSpec/Minitest naming
		return matchesAnyGlob(path, slices.Concat(defaultTestPaths, defaultTestFilenames, rubyTestPathPatterns))

	case model.Rust:
		// Rust: default folders (covers the "tests/" integration test dir) + tests.rs module convention
		return matchesAnyGlob(path, slices.Concat(defaultTestPaths, defaultTestFilenames, rustTestPathPatterns))

	case model.Elixir:
		return matchesAnyGlob(path, slices.Concat(defaultTestPaths, defaultTestFilenames, elixirTestPathPatterns))

	case model.Swift:
		return matchesAnyGlob(path, slices.Concat(defaultTestPaths, defaultTestFilenames, swiftTestPathPatterns))

	case model.Dart:
		return matchesAnyGlob(path, dartTestPathPatterns)

	default:
		// For other languages we don't classify here
		return false
	}
}

// ---------- Import-based detection ----------

func hasTestLikeImport(language model.Language, code, path string) bool {
	switch language {
	case model.Go:
		return goHasTestLikeImport(code, path)
	case model.Java:
		return javaHasTestLikeImport(code)
	case model.Python:
		return pythonHasTestLikeImport(code)
	case model.Kotlin:
		return kotlinHasTestLikeImport(code)
	case model.PHP:
		return phpHasTestLikeImport(code)
	case model.Ruby:
		return rubyHasTestLikeImport(code)
	case model.Elixir:
		return elixirHasTestLikeImport(code)
	case model.Swift:
		return swiftHasTestLikeImport(code)
	case model.Dart:
		return dartHasTestLikeImport(code)
	default:
		return false
	}
}

// ----- Go import detection -----

func goHasTestLikeImport(code, path string) bool {
	fset := token.NewFileSet()
	// Parse only imports; we don't need full AST.
	file, err := parser.ParseFile(fset, path, code, parser.ImportsOnly)
	if err != nil || file == nil {
		return false
	}

	testImportPrefixes := []string{
		"github.com/go-check/check",
		"github.com/onsi/ginkgo",
		"github.com/h2non/gock",
		"github.com/smartystreets/goconvey",
		"github.com/onsi/gomega",
		"github.com/golang/mock",
		"go.uber.org/mock",
		"github.com/petergtz/pegomock",
		"testing",
		"github.com/stretchr/testify",
	}

	for _, spec := range file.Imports {
		raw := strings.Trim(spec.Path.Value, `"`) // "testing" or "github.com/stretchr/testify/require"
		for _, prefix := range testImportPrefixes {
			if raw == prefix || strings.HasPrefix(raw, prefix+"/") {
				return true
			}
		}
	}
	return false
}

// ----- Java import detection -----
func javaHasTestLikeImport(code string) bool {
	javaTestPrefixes := []string{
		"org.apache.camel.test",
		"org.awaitility",
		"org.jboss.arquillian",
		"org.assertj",
		"io.cucumber",
		"org.dbunit",
		"org.easymock",
		"org.jbehave",
		"org.openjdk.jmh",
		"org.junit",
		"com.intuit.karate",
		"org.mockito",
		"au.com.dius.pact",
		"org.powermock",
		"io.restassured",
		"org.seleniumhq.selenium",
		"org.openqa.selenium",
		"org.spockframework",
		"org.testcontainers",
		"org.testfx",
		"org.testng",
		"com.github.tomakehurst.wiremock",
	}

	scanner := bufio.NewScanner(strings.NewReader(code))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if !strings.HasPrefix(line, "import ") {
			continue
		}
		// Strip "import" and optional "static".
		line = strings.TrimSpace(strings.TrimPrefix(line, "import"))
		if strings.HasPrefix(line, "static ") {
			line = strings.TrimSpace(strings.TrimPrefix(line, "static"))
		}
		// Drop trailing ';'
		if i := strings.Index(line, ";"); i >= 0 {
			line = line[:i]
		}
		// Now line should be a FQN like org.junit.Assert or org.mockito.Mockito
		for _, prefix := range javaTestPrefixes {
			if line == prefix || strings.HasPrefix(line, prefix+".") {
				return true
			}
		}
	}
	return false
}

// ----- Kotlin import detection -----
func kotlinHasTestLikeImport(code string) bool {
	kotlinTestPrefixes := []string{
		"org.junit",
		"kotlin.test",
		"io.kotest",
		"io.kotlintest",
		"io.mockk",
		"org.mockito",
		"com.nhaarman.mockitokotlin2",
		"org.mockito.kotlin",
		"org.spekframework",
		"org.assertj",
		"org.amshove.kluent",
		"org.testng",
		"org.robolectric",
		"androidx.test",
	}

	scanner := bufio.NewScanner(strings.NewReader(code))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if !strings.HasPrefix(line, "import ") {
			continue
		}
		// Strip "import" keyword (Kotlin imports have no trailing ';').
		line = strings.TrimSpace(strings.TrimPrefix(line, "import"))
		// Drop an "as alias" suffix, then a trailing ".*" wildcard.
		if i := strings.IndexByte(line, ' '); i >= 0 {
			line = line[:i]
		}
		line = strings.TrimSuffix(line, ".*")
		// Now line should be a FQN like org.junit.jupiter.api.Test
		for _, prefix := range kotlinTestPrefixes {
			if line == prefix || strings.HasPrefix(line, prefix+".") {
				return true
			}
		}
	}
	return false
}

// ----- Python import detection -----
func pythonHasTestLikeImport(code string) bool {
	pyTestPrefixes := []string{
		"behave",
		"doctest",
		"hypothesis",
		"nox",
		"pytest",
		"pytest_bdd",
		"testify",
		"unittest",
		"unittest2",
	}

	scanner := bufio.NewScanner(strings.NewReader(code))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Handle "import X" or "import X as Y"
		if strings.HasPrefix(line, "import ") {
			rest := strings.TrimSpace(strings.TrimPrefix(line, "import"))
			// Basic split: "pytest", "pytest as p"
			fields := strings.Fields(rest)
			if len(fields) > 0 {
				mod := fields[0] // first module in "import pytest"
				if pythonImportMatches(mod, pyTestPrefixes) {
					return true
				}
			}
		}

		// Handle "from X import Y"
		if strings.HasPrefix(line, "from ") {
			rest := strings.TrimSpace(strings.TrimPrefix(line, "from"))
			fields := strings.Fields(rest)
			if len(fields) > 0 {
				mod := fields[0] // module in "from pytest import some_fixture"
				if pythonImportMatches(mod, pyTestPrefixes) {
					return true
				}
			}
		}
	}
	return false
}

func pythonImportMatches(module string, prefixes []string) bool {
	for _, prefix := range prefixes {
		if module == prefix || strings.HasPrefix(module, prefix+".") {
			return true
		}
	}
	return false
}

// ----- PHP import detection -----
func phpHasTestLikeImport(code string) bool {
	// PHP uses "use Vendor\Namespace\Class;" statements.
	phpTestPrefixes := []string{
		"PHPUnit\\",
		"Mockery\\",
		"Codeception\\",
		"Behat\\",
		"Prophecy\\",
		"AspectMock\\",
	}

	scanner := bufio.NewScanner(strings.NewReader(code))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if !strings.HasPrefix(line, "use ") {
			continue
		}
		rest := strings.TrimSpace(strings.TrimPrefix(line, "use"))
		// Drop trailing ';'
		if i := strings.Index(rest, ";"); i >= 0 {
			rest = rest[:i]
		}
		// Drop "as Alias" suffix
		if i := strings.Index(rest, " as "); i >= 0 {
			rest = rest[:i]
		}
		rest = strings.TrimSpace(rest)
		for _, prefix := range phpTestPrefixes {
			if strings.HasPrefix(rest, prefix) {
				return true
			}
		}
	}
	return false
}

// ----- Ruby import detection -----
func rubyHasTestLikeImport(code string) bool {
	// Ruby uses require/require_relative for loading test frameworks.
	rubyTestLibs := []string{
		"rspec",
		"minitest",
		"test/unit",
		"shoulda",
		"cucumber",
		"capybara",
		"factory_bot",
		"faker",
	}

	scanner := bufio.NewScanner(strings.NewReader(code))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		// Match: require 'rspec', require "minitest/autorun", require_relative 'spec_helper'
		if !strings.HasPrefix(line, "require") {
			continue
		}
		for _, lib := range rubyTestLibs {
			if strings.Contains(line, lib) {
				return true
			}
		}
	}
	return false
}

// ----- Elixir test framework detection -----
func elixirHasTestLikeImport(code string) bool {
	elixirTestPatterns := []string{
		"use ExUnit.Case",
		"use ExUnit.CaseTemplate",
		"import ExUnit.Assertions",
	}

	for _, pattern := range elixirTestPatterns {
		if strings.Contains(code, pattern) {
			return true
		}
	}
	return false
}

func swiftHasTestLikeImport(code string) bool {
	swiftTestModules := map[string]struct{}{
		"XCTest": {},
		"Quick":  {},
		"Nimble": {},
	}

	scanner := bufio.NewScanner(strings.NewReader(code))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		line = strings.TrimPrefix(line, "@testable ")
		if !strings.HasPrefix(line, "import ") {
			continue
		}
		fields := strings.Fields(strings.TrimPrefix(line, "import"))
		if len(fields) == 0 {
			continue
		}
		module := fields[len(fields)-1]
		if i := strings.IndexByte(module, '.'); i >= 0 {
			module = module[:i]
		}
		if _, ok := swiftTestModules[module]; ok {
			return true
		}
	}
	return false
}

func dartHasTestLikeImport(code string) bool {
	testPackages := []string{
		"package:test/",
		"package:flutter_test/",
		"package:integration_test/",
		"package:mockito/",
		"package:mocktail/",
	}
	return containsAnyString(code, testPackages)
}

func containsAnyString(value string, candidates []string) bool {
	for _, candidate := range candidates {
		if strings.Contains(value, candidate) {
			return true
		}
	}
	return false
}
